In [1]:
import numpy as np
class McCullochPittsNeuron:
    def __init__(self, threshold):
        """
        Inicializa la neurona con un umbral.
        :param threshold: Umbral para la función de activación
        """
        self.threshold = threshold

    def activate(self, inputs):
        """
        Calcula la salida de la neurona basada en las entradas.
        :param inputs: Lista o array de entradas (0 o 1)
        :return: Salida de la neurona (0 o 1)
        """
        # Calcula la suma de las entradas
        print(inputs)
        weighted_sum = inputs.sum() # suma todos los elementos
        
        # Aplica la función de activación (umbral)
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

# Configura el umbral para la función AND

threshold = 2  # Umbral para que la suma sea al menos 2 para producir salida 1

# Crea la neurona
neuron = McCullochPittsNeuron(threshold)

# Prueba la neurona con todas las combinaciones de entradas para la función AND
inputs = np.array([
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
])

# Imprime las salidas para cada combinación de entradas
for inp in inputs:
    output = neuron.activate(inp)
    print(f"Entrada: {inp}, Salida: {output}")

[0 0]
Entrada: [0 0], Salida: 0
[0 1]
Entrada: [0 1], Salida: 0
[1 0]
Entrada: [1 0], Salida: 0
[1 1]
Entrada: [1 1], Salida: 1


## Ejercicio1: 

### Diseñar e implementar en una clase una unidad McCulloch–Pitts capaz de reconocer la función AND y OR para 3 variables.

In [ ]:
import numpy as np
class McCullochPittsNeuron:
    def __init__(self, threshold):
        """
        Inicializa la neurona con un umbral.
        :param threshold: Umbral para la función de activación
        """
        self.threshold = threshold

    def activate(self, inputs):
        """
        Calcula la salida de la neurona basada en las entradas.
        :param inputs: Lista o array de entradas (0 o 1)
        :return: Salida de la neurona (0 o 1)
        """
        # Calcula la suma de las entradas
        print(inputs)
        weighted_sum = inputs.sum() # suma todos los elementos
        
        # Aplica la función de activación (umbral)
        activacion = 0 
        if weighted_sum >= self.threshold: 
            activacion = 1
        return activacion

# Configura el umbral para la función AND

threshold_AND = 3  # Umbral para que la suma sea al menos 3 para producir salida 1
threshold_OR = 1  # Umbral al menos 1 para producir salida 1
# Crea la neurona
neuron_AND = McCullochPittsNeuron(threshold_AND)
neuron_OR = McCullochPittsNeuron(threshold_OR)
# Prueba la neurona con todas las combinaciones de entradas para la función AND
inputs = np.array([
    [0, 0, 0],
    [0, 0, 1],
    [0, 1, 0],
    [0, 1, 1],
    [1, 0, 0],
    [1, 0, 1],
    [1, 1, 0],
    [1, 1, 1]
])

# Imprime las salidas para cada combinación de entradas AND
print("Funcion AND")
for inp in inputs:
    output = neuron_AND.activate(inp)
    print(f"Entrada: {inp}, Salida: {output}")

# Imprime las salidas para cada combinación de entradas OR
print("\nFuncion OR")
for inp in inputs:
    output = neuron_OR.activate(inp)
    print(f"Entrada: {inp}, Salida: {output}")

Funcion AND
[0 0 0]
Entrada: [0 0 0], Salida: 0
[0 0 1]
Entrada: [0 0 1], Salida: 0
[0 1 0]
Entrada: [0 1 0], Salida: 0
[0 1 1]
Entrada: [0 1 1], Salida: 0
[1 0 0]
Entrada: [1 0 0], Salida: 0
[1 0 1]
Entrada: [1 0 1], Salida: 0
[1 1 0]
Entrada: [1 1 0], Salida: 0
[1 1 1]
Entrada: [1 1 1], Salida: 1

Funcion OR
[0 0 0]
Entrada: [0 0 0], Salida: 0
[0 0 1]
Entrada: [0 0 1], Salida: 1
[0 1 0]
Entrada: [0 1 0], Salida: 1
[0 1 1]
Entrada: [0 1 1], Salida: 1
[1 0 0]
Entrada: [1 0 0], Salida: 1
[1 0 1]
Entrada: [1 0 1], Salida: 1
[1 1 0]
Entrada: [1 1 0], Salida: 1
[1 1 1]
Entrada: [1 1 1], Salida: 1


## Ejercicio 2: 

### Diseñar e implementar una unidad McCulloch–Pitts capaz de reconocer la letra "T" digitalizada en una matriz de 10 × 10 píxeles. Los píxeles oscuros deben codificarse como unos y los píxeles blancos como ceros.

In [42]:
import numpy as np

class McCullochPittsNeuron:
    def __init__(self, threshold):
        self.threshold = threshold

    def activate(self, inputs):
        total = np.sum(inputs)
        if total >= self.threshold:
            return 1
        else:
            return 0


# Crear la matriz de la letra "T" (10x10)
T = np.zeros((10, 10), dtype=int)
# Barra horizontal (fila 0)
T[0, :] = 1
# Barra vertical (columna central)
T[1:, 4] = 1



# Umbral = cantidad total de píxeles de la "T" para reconocerla
umbral = np.sum(T)

# Crear la neurona
neuron = McCullochPittsNeuron(threshold=umbral)

# Probar la neurona con la letra T
print("Probando matriz 'T'")
print(T)
output = neuron.activate(T)
print("Salida para la letra T:", output)

# Probar la neurona con otra matriz (diferente letra o patrón)
O = np.zeros((10,10), dtype=int)  # matriz vacía
print("Probando matriz de '0'")
print(O)
output2 = neuron.activate(O)
print("Salida para otra matriz:", output2)


L = np.zeros((10, 10), dtype=int)
# Barra horizontal (fila 0)
L[0, :] = 1
# Barra vertical (columna central)
L[1:, 0] = 1
print("Probando matriz de 'L'")
print(L)
output3 = neuron.activate(L)
print("Salida para otra matriz 'L':", output3)

Probando matriz 'T'
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]
Salida para la letra T: 1
Probando matriz de '0'
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Salida para otra matriz: 0
Probando matriz de 'L'
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]
Salida para otra matriz 'L': 1


In [44]:
T = np.zeros((10, 10), dtype=int)

# Barra horizontal (fila 0)
T[0, :] = 1
print(T)
# Barra vertical (columna central)
T[1:, 4] = 1
print(T)

[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
[[1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]]


In [40]:
L = np.zeros((10, 10), dtype=int)

# Barra horizontal (fila 0)
L[0, :] = 1

# Barra vertical (columna central)
L[1:, 0] = 1
print(L)



[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]]


In [1]:
X = np.array([1,2,5])
print("X=")
print(X)
B = np.array([1,2])
print("B=")
print(B)
W = np.array([[3,1,4],
              [2,7,5]])
print("W=")
print(W)
print("W_t=")
W_t = np.transpose(W) 
print(W_t)
print("Y = (X * W_t) + B")
Y = (X@W_t)+B
print("Y=")
print(Y)

NameError: name 'np' is not defined

In [5]:
X = np.array([[1,2],
             [2,3],
             [4,1]])
W = np.array([[2,5],
             [4,3],
             [2,1]])
B = np.array([[2,3,2],
             [2,3,2],
             [2,3,2]])

Y = X@W.T+B
print(Y)

[[14 13  6]
 [21 20  9]
 [15 22 11]]
